package eu.relay4u.authservicebe.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    BAD_REQUEST,
    REGISTER_INVALID,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    EMAIL_NOT_VERIFIED,
    EMAIL_ALREADY_VERIFIED,
    EMAIL_ALREADY_REGISTERED,
    INVALID_VERIFICATION_CODE,
    VERIFICATION_CODE_EXPIRED,
    VERIFICATION_BLOCKED,
    RESEND_RATE_LIMIT,
    PASSWORD_NOT_SET,
    ACCESS_DENIED,
    INTERNAL_ERROR
}
